export const refundAnalysisData = {
  sourceLabel: "退款列表20260723-3.xlsx",
  courseLabel: "2026春季课",
  rowCount: 8873,
  reasonCount: 23,
  remarkTotalCount: 7554,
  timeRange: {
    start: "2025-10-29 09:20:43",
    end: "2026-07-20 18:51:04",
  },
  statusBreakdown: [
    { label: "退课", value: 8255 },
    { label: "仅退款", value: 618 },
  ],
  specialRefundRemarkBreakdown: [
    { label: "退课", value: 51 },
    { label: "仅退款", value: 40 },
  ],
  typeBreakdown: [
    { label: "课前退", value: 4260 },
    { label: "课后退", value: 3995 },
    { label: "--", value: 608 },
    { label: "未知", value: 10 },
  ],
  methodBreakdown: [
    { label: "富友", value: 8849 },
    { label: "现金", value: 15 },
    { label: "银行转账", value: 5 },
    { label: "财务处理", value: 4 },
  ],
  reasonBreakdown: [
    { label: "其他", value: 6398 },
    { label: "时间冲突", value: 1200 },
    { label: "退费重报", value: 548 },
    { label: "线上课返利", value: 222 },
    { label: "高端班半价", value: 207 },
    { label: "距离问题", value: 154 },
    { label: "课程问题", value: 30 },
    { label: "教师问题", value: 18 },
    { label: "比心计划：20%", value: 22 },
    { label: "特殊关系：80%", value: 11 },
    { label: "比心计划：30%", value: 10 },
    { label: "比心计划：40%", value: 10 },
    { label: "特殊审批折扣：80%", value: 8 },
    { label: "比心计划：50%", value: 7 },
    { label: "内部员工子女2折优惠（包含亲兄弟姐妹）：20%", value: 7 },
    { label: "比心计划：70%", value: 5 },
    { label: "比心计划：60%", value: 5 },
    { label: "比心计划：10%", value: 4 },
    { label: "特殊关系：90%", value: 3 },
    { label: "特殊审批折扣：90%", value: 2 },
    { label: "特殊关系：70%", value: 2 },
    { label: "特殊退费", value: 1 },
    { label: "业务办理错误", value: 1 },
  ],
  subjectBreakdown: [
    { label: "信息学算法", value: 6027 },
    { label: "信息学实验P", value: 1255 },
    { label: "信息学语言传播", value: 1199 },
    { label: "信息学实验C", value: 381 },
    { label: "国文素养", value: 11 },
  ],
  gradeBreakdown: [
    { label: "初三", value: 1625 },
    { label: "初二", value: 1503 },
    { label: "初一", value: 1281 },
    { label: "三年级", value: 1012 },
    { label: "五年级", value: 856 },
    { label: "六年级", value: 831 },
    { label: "四年级", value: 696 },
    { label: "二年级", value: 329 },
  ],
  campusBreakdown: [
    { label: "MeiGuiY", value: 716 },
    { label: "NanXunM", value: 540 },
    { label: "BaLi-DuShi", value: 510 },
    { label: "SanXiaoK", value: 456 },
    { label: "SiPaiLou", value: 446 },
    { label: "FanHuaDaD", value: 440 },
  ],
  branchBreakdown: [
    { label: "YiJingLu", value: 3543 },
    { label: "DaXiDi", value: 2303 },
    { label: "SiLiHe", value: 271 },
    { label: "XiangShuW", value: 262 },
    { label: "AnNongD", value: 259 },
    { label: "HuangShanL", value: 188 },
  ],
  monthlyTrend: [
    { label: "2025-12", count: 838 },
    { label: "2026-01", count: 756 },
    { label: "2026-02", count: 843 },
    { label: "2026-03", count: 2394 },
    { label: "2026-04", count: 1376 },
    { label: "2026-05", count: 1412 },
    { label: "2026-06", count: 798 },
    { label: "2026-07", count: 8 },
  ],
  remarkAnalysisBreakdown: [
    { label: "主动放弃继续上课", value: 2201 },
    { label: "时间安排冲突", value: 1052 },
    { label: "客观家庭因素", value: 615 },
    { label: "学习适配问题", value: 534 },
    { label: "业务政策/优惠", value: 398 },
  ],
  remarkCloud: [
    { label: "孩子不愿意上", value: 211 },
    { label: "孩子不想上了", value: 189 },
    { label: "孩子不想上", value: 134 },
    { label: "不考虑了", value: 125 },
    { label: "不想上了", value: 120 },
    { label: "退费重报", value: 117 },
    { label: "时间冲突", value: 110 },
    { label: "孩子跟不上", value: 100 },
    { label: "没时间上", value: 82 },
    { label: "时间不合适", value: 82 },
    { label: "孩子不愿意上了", value: 76 },
    { label: "个人原因", value: 64 },
    { label: "跟不上", value: 56 },
    { label: "坚持退费", value: 54 },
    { label: "不考虑转班", value: 40 },
    { label: "不上了", value: 39 },
    { label: "孩子不愿意", value: 35 },
    { label: "暂时不上了", value: 32 },
    { label: "需要退费", value: 31 },
    { label: "时间紧张", value: 28 },
    { label: "孩子生病了", value: 27 },
    { label: "不考虑", value: 26 },
    { label: "时间安排不过来", value: 25 },
    { label: "要退费", value: 24 },
    { label: "没时间", value: 23 },
    { label: "听不懂", value: 23 },
    { label: "搬家了", value: 22 },
    { label: "上不了", value: 21 },
    { label: "高端班半价", value: 20 },
    { label: "没有时间上", value: 20 },
    { label: "时间冲突了", value: 19 },
    { label: "孩子不舒服", value: 18 },
    { label: "孩子不想学了", value: 18 },
    { label: "要退课", value: 18 },
    { label: "换老师了", value: 17 },
    { label: "效果不好", value: 17 },
    { label: "孩子生病", value: 16 },
    { label: "不在合肥", value: 16 },
    { label: "不想上", value: 16 },
    { label: "不考虑调课", value: 16 },
    { label: "有点跟不上", value: 16 },
    { label: "课程冲突", value: 16 },
    { label: "太远了", value: 16 },
    { label: "不考虑看资料视频", value: 15 },
    { label: "先退了", value: 14 },
    { label: "已经跟老师沟通过了", value: 14 },
    { label: "暂时不想上了", value: 14 },
    { label: "生病了", value: 13 },
    { label: "不需要了", value: 13 },
    { label: "自身原因", value: 12 },
    { label: "望批准", value: 12 },
    { label: "孩子没有时间", value: 12 },
    { label: "上不了了", value: 11 },
    { label: "没时间上课", value: 11 },
    { label: "孩子身体不舒服", value: 11 },
    { label: "孩子不愿意去", value: 11 },
    { label: "孩子有点跟不上", value: 11 },
    { label: "没有时间上了", value: 11 },
    { label: "课太多了", value: 11 },
  ],
  refundDelayMetrics: {
    onlineRebate: {
      count: 222,
      averageSeconds: 15636133.653153153,
    },
    highEndHalf: {
      count: 207,
      averageSeconds: 8675052.8647343,
    },
    bxPlan: {
      count: 63,
      averageSeconds: 3699907.2,
    },
  },
  previewRows: [
    {
      time: "2026-07-20 18:51:04",
      name: "吴欣怡",
      reason: "特殊退费",
      method: "富友",
      course: "2026六年级信息学算法【春季】",
      campus: "HaiTang",
      handler: "张哓雨",
      orderStatus: "仅退款",
    },
    {
      time: "2026-07-18 21:22:02",
      name: "夏邓珵",
      reason: "高端班半价",
      method: "富友",
      course: "2026三年级信息学算法【春季】",
      campus: "HuangShanL",
      handler: "赵玲玲",
      orderStatus: "仅退款",
    },
    {
      time: "2026-07-14 11:45:48",
      name: "左亦宸",
      reason: "时间冲突",
      method: "富友",
      course: "2026二年级信息学算法【春季】",
      campus: "XiuNingLu",
      handler: "张哓雨",
      orderStatus: "仅退款",
    },
    {
      time: "2026-07-08 16:22:03",
      name: "程象千",
      reason: "教师问题",
      method: "富友",
      course: "2026初二信息学语言传播【春季】",
      campus: "NanXunM",
      handler: "张哓雨",
      orderStatus: "仅退款",
    },
    {
      time: "2026-07-06 14:38:44",
      name: "吴彦霖",
      reason: "高端班半价",
      method: "富友",
      course: "2026二年级信息学算法【春季】",
      campus: "AnNongD",
      handler: "吴彩旗",
      orderStatus: "仅退款",
    },
    {
      time: "2026-07-06 12:13:12",
      name: "余睿涵",
      reason: "其他",
      method: "富友",
      course: "2026六年级信息学算法【春季】",
      campus: "BaLi-DuShi",
      handler: "张哓雨",
      orderStatus: "仅退款",
    },
    {
      time: "2026-07-01 15:20:19",
      name: "季菀宁",
      reason: "高端班半价",
      method: "富友",
      course: "2026四年级信息学算法【寒假】",
      campus: "SanXiaoK",
      handler: "黄朝晖",
      orderStatus: "仅退款",
    },
    {
      time: "2026-07-01 15:20:19",
      name: "季菀宁",
      reason: "高端班半价",
      method: "富友",
      course: "2026四年级信息学算法【春季】",
      campus: "SanXiaoK",
      handler: "黄朝晖",
      orderStatus: "仅退款",
    },
    {
      time: "2026-06-30 15:08:37",
      name: "高玥晗",
      reason: "线上课返利",
      method: "富友",
      course: "2026高一信息学实验P【春季】",
      campus: "线上",
      handler: "操倩",
      orderStatus: "仅退款",
    },
    {
      time: "2026-06-30 15:05:47",
      name: "阮梓淼",
      reason: "线上课返利",
      method: "富友",
      course: "2026高一信息学算法【春季】",
      campus: "线上",
      handler: "操倩",
      orderStatus: "仅退款",
    },
    {
      time: "2026-06-29 19:50:03",
      name: "章璟禾",
      reason: "线上课返利",
      method: "富友",
      course: "2026初二信息学实验C【春季】",
      campus: "线上",
      handler: "刘菊文",
      orderStatus: "仅退款",
    },
    {
      time: "2026-06-29 19:42:47",
      name: "裴安琪",
      reason: "线上课返利",
      method: "富友",
      course: "2026初三信息学实验C【春季】",
      campus: "线上",
      handler: "刘菊文",
      orderStatus: "仅退款",
    },
  ],
} as const;
